---
title: "Project"
---

Your final assignment in this course will be to work on a group data science project. The goal of the project is to go through the complete data science process to answer questions you have about some topic of your choosing. You will need to acquire your data, design your visualizations, run analyses, and communicate the results.

### Project Dates

A rough timeline of the project is:

* Week X: Proposal due
* Week X: Data collection and cleaning finished
* Week X: EDA finished
* Week X: Modeling finished
* Finals: Written report and oral presentation

### Teams

### R Markdown Process Book

An important part of your project is your R Markdown process book. Your process book details the steps you take in developing your solution, including how you collected the data, alternative solutions you tried, describing statistical methods you used, and the insights you got. Equally important to your final results is how you got there! Your process book is the place you describe and document the space of possibilities you explored at each step of your project. We strongly advise you to include many visualizations in your process book. Your process book should include the following topics. Depending on your project type the amount of discussion you devote to each of them will vary:

* Overview and Motivation: Provide an overview of the project goals and the motivation for it. Consider that this will be read by people who did not see your project proposal.

* Related Work: Anything that inspired you, such as a paper, a web site, or something we discussed in class.

* Initial Questions: What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis? 

* Data: Source, scraping method, cleanup, storage, etc.

* Exploratory Data Analysis: What visualizations did you use to look at your data in different ways? What are the different statistical methods you considered? Justify the decisions you made, and show any major changes to your ideas. How did you reach these conclusions?

* Final Analysis: What did you learn about the data? How did you answer the questions? How can you justify your answers?

* Presentation: Present your final results in a compelling and engaging way using text, visualizations, images, and videos.


### Code

I expect you to write high-quality and readable R code in your process book. You should strive for doing things the right way and think about aspects such as reusability, error handling, etc. We also expect you to document your code.